// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "App": {
    "title": "MarketLens",
    "tagline": "Track, compare, and rank companies with real financial data."
  },
  "Nav": {
    "ranking": "Company Ranking",
    "details": "Company Details"
  },
  "Ranking": {
    "rankingBy": "Ranking by",
    "company": "Company",
    "sector": "Sector",
    "avgRank": "Avg Rank",
    "na": "N/A",
    "addRatio": "Add ratio",
    "removeRatio": "Remove {label}"
  },
  "Details": {
    "companiesHeading": "Companies (up to {max})",
    "ratios": "Ratios",
    "yearRange": "Year range",
    "to": "to",
    "searchPlaceholder": "Search ticker or name...",
    "noCompaniesFound": "No companies found",
    "selectPrompt": "Select a company to get started",
    "compareHint": "You can compare up to {max} companies side by side",
    "addCompany": "Add company",
    "addRatio": "Add ratio",
    "removeCompany": "Remove {ticker}",
    "removeRatio": "Remove {label}"
  },
  "Disclaimer": {
    "title": "Disclaimer",
    "body": "This application is for <strong>educational and demonstration purposes only</strong>. Financial data is sourced from Yahoo Finance via the yfinance library and may be inaccurate, delayed, or incomplete. Nothing on this site constitutes financial advice. Do not make investment decisions based on this data.",
    "accept": "I understand"
  }
};
export default messages;